[theme]
primaryColor = "#4C7C83"  # Teal
backgroundColor = "#F4F4F4"  # Off-White
secondaryBackgroundColor = "#FFFFFF"  # White
textColor = "#000000"  # Black
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
